package br.com.view;


import br.com.controller.ColecaoController;
import br.com.controller.FuncionarioController;
import br.com.controller.FuncionarioController;
import br.com.model.negocio.Colecao;
import br.com.model.negocio.Funcionario;
import br.com.model.negocio.Funcionario;
import br.com.validators.Validadores;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rosicléia Frasson
 */
public class InserirColecaoGui extends javax.swing.JFrame {
    ColecaoTableModel model;
    /**
     * Creates new form InserirFuncionarioGui
     */
    public InserirColecaoGui(ColecaoTableModel mtb) {
        initComponents();
        model = mtb;
        carregarComboFuncionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaogrupo = new javax.swing.ButtonGroup();
        painelCentro = new javax.swing.JPanel();
        nomeTxt = new javax.swing.JLabel();
        campoTema = new javax.swing.JTextField();
        sexoTxt = new javax.swing.JLabel();
        dataTxt = new javax.swing.JLabel();
        emailTxt = new javax.swing.JLabel();
        campoEstacao = new javax.swing.JTextField();
        painelCabecalho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelRodape = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoLimpar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        campoDataAprovacao = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        comboFuncionarioResponsavel = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        checkFeminino = new javax.swing.JCheckBox();
        checkMasculino = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Marca");
        getContentPane().setLayout(null);

        painelCentro.setBackground(new java.awt.Color(255, 255, 255));
        painelCentro.setLayout(null);

        nomeTxt.setText("Tema:");
        painelCentro.add(nomeTxt);
        nomeTxt.setBounds(60, 130, 140, 14);
        painelCentro.add(campoTema);
        campoTema.setBounds(110, 130, 240, 20);

        sexoTxt.setText("Genero:");
        painelCentro.add(sexoTxt);
        sexoTxt.setBounds(50, 220, 70, 14);

        dataTxt.setText("Data de aprovação do modelo:");
        painelCentro.add(dataTxt);
        dataTxt.setBounds(380, 130, 270, 14);

        emailTxt.setText("Estação:");
        painelCentro.add(emailTxt);
        emailTxt.setBounds(50, 170, 80, 14);
        painelCentro.add(campoEstacao);
        campoEstacao.setBounds(110, 170, 240, 20);

        painelCabecalho.setBackground(new java.awt.Color(204, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/add_user-64.png"))); // NOI18N
        jLabel1.setText("Inserir Coleção");

        javax.swing.GroupLayout painelCabecalhoLayout = new javax.swing.GroupLayout(painelCabecalho);
        painelCabecalho.setLayout(painelCabecalhoLayout);
        painelCabecalhoLayout.setHorizontalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCabecalhoLayout.createSequentialGroup()
                .addContainerGap(379, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );
        painelCabecalhoLayout.setVerticalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        painelCentro.add(painelCabecalho);
        painelCabecalho.setBounds(-20, 20, 940, 60);

        painelRodape.setBackground(new java.awt.Color(204, 153, 255));
        painelRodape.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/abbb.png"))); // NOI18N
        painelRodape.add(jLabel2);
        jLabel2.setBounds(0, 11, 298, 57);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/Cópia de ddd.png"))); // NOI18N
        painelRodape.add(jLabel3);
        jLabel3.setBounds(595, 20, 347, 48);

        botaoLimpar.setBackground(new java.awt.Color(255, 255, 255));
        botaoLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoLimpar.setForeground(new java.awt.Color(153, 0, 255));
        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/limpar.png"))); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        painelRodape.add(botaoLimpar);
        botaoLimpar.setBounds(330, 10, 117, 41);

        botaoSalvar.setBackground(new java.awt.Color(255, 255, 255));
        botaoSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoSalvar.setForeground(new java.awt.Color(153, 0, 255));
        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/salvar.png"))); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });
        painelRodape.add(botaoSalvar);
        botaoSalvar.setBounds(460, 10, 130, 41);

        painelCentro.add(painelRodape);
        painelRodape.setBounds(0, 280, 870, 70);

        try {
            campoDataAprovacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelCentro.add(campoDataAprovacao);
        campoDataAprovacao.setBounds(570, 130, 240, 20);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        painelCentro.add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 10);

        painelCentro.add(comboFuncionarioResponsavel);
        comboFuncionarioResponsavel.setBounds(570, 170, 240, 20);

        jLabel4.setText("Funcionario Responsavel:");
        painelCentro.add(jLabel4);
        jLabel4.setBounds(420, 170, 150, 20);

        checkFeminino.setBackground(new java.awt.Color(255, 255, 255));
        checkFeminino.setText("Feminino");
        painelCentro.add(checkFeminino);
        checkFeminino.setBounds(120, 220, 100, 23);

        checkMasculino.setBackground(new java.awt.Color(255, 255, 255));
        checkMasculino.setText("Masculino");
        painelCentro.add(checkMasculino);
        checkMasculino.setBounds(250, 220, 100, 23);

        getContentPane().add(painelCentro);
        painelCentro.setBounds(0, 0, 841, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Colecao m = new Colecao();

        if ((campoTema.getText().length() <= 0)

                || ((campoEstacao.getText().length() <= 0)

                    || (campoDataAprovacao.getText().length() <= 0))){
        
        } else {

            m.setTema(campoTema.getText());
            m.setEstacao(campoEstacao.getText());
            m.setFuncionarioReponsavel((Funcionario)comboFuncionarioResponsavel.getSelectedItem());
            try{

                m.setDataAprovacaoModelo(new SimpleDateFormat("dd/mm/yyyy").parse(campoDataAprovacao.getText()));

            } catch (ParseException ex){
                System.out.println("Erro na conversão de datas" + ex.getMessage());
            }
             if (checkFeminino.isSelected()){
               m.setGenero(true);
       
               
           }else{
               m.setGenero(false);
           }
      
             if (checkMasculino.isSelected()){
               m.setGenero(true);
       
               
           }else{
               m.setGenero(false);
           }
             
            ColecaoController mc = new ColecaoController();
            if(mc.salvar(m)){
                model.addColecao(pesquisar(m.getTema()));
            }
            dispose();
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoTema.setText("");
        campoEstacao.setText("");
        campoDataAprovacao.setText("");
        comboFuncionarioResponsavel.setSelectedIndex(0);
        checkFeminino.setSelected(false);
        checkMasculino.setSelected(false);
    }//GEN-LAST:event_botaoLimparActionPerformed

    private Colecao pesquisar (String tema){
        ColecaoController mc = new ColecaoController();
        return mc.listaColecaoByTema(tema);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.ButtonGroup botaogrupo;
    private javax.swing.JFormattedTextField campoDataAprovacao;
    private javax.swing.JTextField campoEstacao;
    private javax.swing.JTextField campoTema;
    private javax.swing.JCheckBox checkFeminino;
    private javax.swing.JCheckBox checkMasculino;
    private javax.swing.JComboBox comboFuncionarioResponsavel;
    private javax.swing.JLabel dataTxt;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeTxt;
    private javax.swing.JPanel painelCabecalho;
    private javax.swing.JPanel painelCentro;
    private javax.swing.JPanel painelRodape;
    private javax.swing.JLabel sexoTxt;
    // End of variables declaration//GEN-END:variables


    
        private void carregarComboFuncionario() {
         //assim como é feito numa JTable, temos o DefaultComboBoxModel que é o model do JComboBox
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) comboFuncionarioResponsavel.getModel();
        //removendo todos os elementos do combo
        comboModel.removeAllElements();
        //cria a lista: java.util.List
        List<Funcionario> funcionarios = new ArrayList<Funcionario>();
        FuncionarioController a = new FuncionarioController();
        funcionarios = a.listarFuncionario();
        
     
        for (int linha = 0; linha <funcionarios.size(); linha++) {
            //pegando a categoria da lista
            Funcionario funcionario = funcionarios.get(linha);
            //adicionando a categoria no combo
            comboModel.addElement(funcionario);
        }
    }
}


