package br.com.view;


import br.com.controller.FuncaoController;
import br.com.controller.FuncionarioController;
import br.com.model.negocio.Funcao;
import br.com.model.negocio.Funcionario;
import br.com.validators.Validadores;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rosicléia Frasson
 */
public class InserirFuncionarioGui extends javax.swing.JFrame {
    FuncionarioTableModel model;
    /**
     * Creates new form InserirFuncionarioGui
     */
    public InserirFuncionarioGui(FuncionarioTableModel mtb) {
        initComponents();
        model = mtb;
        carregarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaogrupo = new javax.swing.ButtonGroup();
        painelCentro = new javax.swing.JPanel();
        nomeTxt = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        funcaoTxt = new javax.swing.JLabel();
        comboFuncao = new javax.swing.JComboBox();
        radioFemino = new javax.swing.JRadioButton();
        radioMasc = new javax.swing.JRadioButton();
        sexoTxt = new javax.swing.JLabel();
        dataTxt = new javax.swing.JLabel();
        checkPermisao = new javax.swing.JCheckBox();
        emailTxt = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        telefoneTxt = new javax.swing.JLabel();
        cpfTxt = new javax.swing.JLabel();
        painelCabecalho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelRodape = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoLimpar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        loginTxt = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        senhaTxt = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JFormattedTextField();
        campoCpf = new javax.swing.JFormattedTextField();
        campoNacimento = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Marca");

        painelCentro.setBackground(new java.awt.Color(255, 255, 255));
        painelCentro.setLayout(null);

        nomeTxt.setText("Nome Completo:");
        painelCentro.add(nomeTxt);
        nomeTxt.setBounds(50, 130, 140, 14);
        painelCentro.add(campoNome);
        campoNome.setBounds(160, 130, 580, 20);

        funcaoTxt.setText("Função:");
        painelCentro.add(funcaoTxt);
        funcaoTxt.setBounds(440, 250, 70, 14);

        painelCentro.add(comboFuncao);
        comboFuncao.setBounds(500, 250, 240, 20);

        radioFemino.setBackground(new java.awt.Color(255, 255, 255));
        botaogrupo.add(radioFemino);
        radioFemino.setText("Femenino");
        painelCentro.add(radioFemino);
        radioFemino.setBounds(160, 330, 100, 23);

        radioMasc.setBackground(new java.awt.Color(255, 255, 255));
        botaogrupo.add(radioMasc);
        radioMasc.setText("Masculino");
        painelCentro.add(radioMasc);
        radioMasc.setBounds(290, 330, 110, 23);

        sexoTxt.setText("Sexo:");
        painelCentro.add(sexoTxt);
        sexoTxt.setBounds(110, 330, 50, 14);

        dataTxt.setText("Data de Nacimento:");
        painelCentro.add(dataTxt);
        dataTxt.setBounds(40, 210, 140, 14);

        checkPermisao.setBackground(new java.awt.Color(255, 255, 255));
        checkPermisao.setText("Permisão em alterar todos os dados do sistema");
        painelCentro.add(checkPermisao);
        checkPermisao.setBounds(490, 330, 350, 23);

        emailTxt.setText("E-mail:");
        painelCentro.add(emailTxt);
        emailTxt.setBounds(100, 170, 80, 14);
        painelCentro.add(campoEmail);
        campoEmail.setBounds(160, 170, 580, 20);

        telefoneTxt.setText("Telefone:");
        painelCentro.add(telefoneTxt);
        telefoneTxt.setBounds(430, 290, 70, 14);

        cpfTxt.setText("Cpf:");
        painelCentro.add(cpfTxt);
        cpfTxt.setBounds(450, 210, 50, 14);

        painelCabecalho.setBackground(new java.awt.Color(204, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/add_user-64.png"))); // NOI18N
        jLabel1.setText("Inserir Funcionario");

        javax.swing.GroupLayout painelCabecalhoLayout = new javax.swing.GroupLayout(painelCabecalho);
        painelCabecalho.setLayout(painelCabecalhoLayout);
        painelCabecalhoLayout.setHorizontalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCabecalhoLayout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
        );
        painelCabecalhoLayout.setVerticalGroup(
            painelCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCabecalhoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painelCentro.add(painelCabecalho);
        painelCabecalho.setBounds(-20, 20, 940, 60);

        painelRodape.setBackground(new java.awt.Color(204, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/abbb.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/Cópia de ddd.png"))); // NOI18N

        botaoLimpar.setBackground(new java.awt.Color(255, 255, 255));
        botaoLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoLimpar.setForeground(new java.awt.Color(153, 0, 255));
        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/limpar.png"))); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoSalvar.setBackground(new java.awt.Color(255, 255, 255));
        botaoSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botaoSalvar.setForeground(new java.awt.Color(153, 0, 255));
        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/rosicleiafrasson/view/imagens/salvar.png"))); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRodapeLayout = new javax.swing.GroupLayout(painelRodape);
        painelRodape.setLayout(painelRodapeLayout);
        painelRodapeLayout.setHorizontalGroup(
            painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRodapeLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelRodapeLayout.setVerticalGroup(
            painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRodapeLayout.createSequentialGroup()
                .addGroup(painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelRodapeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botaoSalvar)
                                .addComponent(botaoLimpar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelCentro.add(painelRodape);
        painelRodape.setBounds(0, 420, 870, 70);

        loginTxt.setText("Login:");
        painelCentro.add(loginTxt);
        loginTxt.setBounds(110, 290, 50, 14);
        painelCentro.add(campoLogin);
        campoLogin.setBounds(160, 290, 240, 20);
        painelCentro.add(campoSenha);
        campoSenha.setBounds(160, 250, 240, 20);

        senhaTxt.setText("Senha:");
        painelCentro.add(senhaTxt);
        senhaTxt.setBounds(100, 250, 70, 14);

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelCentro.add(campoTelefone);
        campoTelefone.setBounds(500, 290, 240, 20);

        try {
            campoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelCentro.add(campoCpf);
        campoCpf.setBounds(500, 210, 240, 20);

        try {
            campoNacimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelCentro.add(campoNacimento);
        campoNacimento.setBounds(160, 210, 240, 20);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        painelCentro.add(jPanel1);
        jPanel1.setBounds(0, 0, 890, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCentro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Funcionario m = new Funcionario();
        
         if ((campoNome.getText().length() <= 0)
                || ((campoCpf.getText().length() <= 0)
                 || ((campoEmail.getText().length() <= 0)
                 || (campoLogin.getText().length() <=0)
                 || (campoNacimento.getText().length() <= 0)
                 || (campoTelefone.getText().length() <= 0)
                 || (campoSenha.getText().length() <= 0)))){
            
              

        } else {


           m.setNome(campoNome.getText());
           m.setEmail(campoEmail.getText());
           m.setSenha(campoSenha.getText());
           m.setLogin(campoLogin.getText());
           m.setTelefone(campoTelefone.getText());
           m.setFuncao((Funcao)comboFuncao.getSelectedItem());
           m.setCpf(campoCpf.getText());
             try{
                 
            m.setDataNacimento(new SimpleDateFormat("dd/mm/yyyy").parse(campoNacimento.getText()));
            
        } catch (ParseException ex){
            System.out.println("Erro na conversão de datas" + ex.getMessage());
        }
           if (radioFemino.isSelected()){
            m.setSexo("Feminino");
             }else{
            m.setSexo("Masculino");
        } 
           
           
           if (checkPermisao.isSelected()){
               m.setPermisao(true);
       
               
           }else{
               m.setPermisao(false);
           }
  
           
        
               
               
           FuncionarioController mc = new FuncionarioController();
            if(mc.salvar(m)){
            model.addModelo(pesquisar(m.getNome(), m.getTelefone()));
            }
            dispose();
}
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoNome.setText("");
        campoEmail.setText(" ");
        campoNacimento.setText("");
        campoSenha.setText("");
        campoLogin.setText("");
        campoCpf.setText(" ");
        campoTelefone.setText("");
        comboFuncao.setSelectedIndex(0);
        radioFemino.setSelected(false);
        checkPermisao.setSelected(false);
        radioMasc.setSelected(false);
    }//GEN-LAST:event_botaoLimparActionPerformed

    private Funcionario pesquisar (String nome, String telefone){
        FuncionarioController mc = new FuncionarioController();
        return mc.listaFuncionarioByNomeTelefone(nome, telefone);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.ButtonGroup botaogrupo;
    private javax.swing.JFormattedTextField campoCpf;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JFormattedTextField campoNacimento;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JCheckBox checkPermisao;
    private javax.swing.JComboBox comboFuncao;
    private javax.swing.JLabel cpfTxt;
    private javax.swing.JLabel dataTxt;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JLabel funcaoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginTxt;
    private javax.swing.JLabel nomeTxt;
    private javax.swing.JPanel painelCabecalho;
    private javax.swing.JPanel painelCentro;
    private javax.swing.JPanel painelRodape;
    private javax.swing.JRadioButton radioFemino;
    private javax.swing.JRadioButton radioMasc;
    private javax.swing.JLabel senhaTxt;
    private javax.swing.JLabel sexoTxt;
    private javax.swing.JLabel telefoneTxt;
    // End of variables declaration//GEN-END:variables

    private void carregarCombo() {
         //assim como é feito numa JTable, temos o DefaultComboBoxModel que é o model do JComboBox
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) comboFuncao.getModel();
        //removendo todos os elementos do combo
        comboModel.removeAllElements();
        //cria a lista: java.util.List
        List<Funcao> funcoes = new ArrayList<Funcao>();
        FuncaoController a = new FuncaoController();
        funcoes = a.listarFuncao();
        
     
        for (int linha = 0; linha <funcoes.size(); linha++) {
            //pegando a categoria da lista
            Funcao funcao = funcoes.get(linha);
            //adicionando a categoria no combo
            comboModel.addElement(funcao);
        }
    }
}
